(ns onyx.state.protocol.db)

(defprotocol State
  (put-extent! [this window-id group extent v])
  (get-extent [this window-id group extent])
  (delete-extent! [this window-id group extent])
  (put-trigger! [this trigger-id group v])
  (get-trigger [this trigger-id group])
  (get-all [this])
  (groups [this window-id])
  (group-extents [this window-id group])
  (drop! [this])
  (export-state [this window-id])
  (export-groups [this])
  (restore! [this stored]))
